#!/usr/bin/env python3
from pathlib import Path

d={}
for l in Path('stage9_outputs/fibre_stage9_build_regression_check.dat').read_text().splitlines():
    p=l.split()
    if len(p)>=2: d[p[0]]=int(float(p[1]))
ones='''stage9_build_stage9_0_output_exists stage9_build_stage9_0_status stage9_build_stage9_entry_allowed_flag stage9_build_stage9_1_allowed_flag stage9_build_stage9_0_dependency_status stage9_build_stage7_closed_marker_exists stage9_build_stage8_closed_marker_exists stage9_build_stage8_total_smoke_output_exists stage9_build_stage8_total_smoke_status stage9_build_stage8_closed_marker_status stage9_build_stage8_no_production_side_effect_status stage9_build_prior_stage_closure_status stage9_build_evidence_output_exists stage9_build_configure_status stage9_build_compile_status stage9_build_used_real_decomp2d_flag stage9_build_fibre_stage_checks_only_off_flag stage9_build_default_production_disabled_flag stage9_build_evidence_status stage9_build_default_production_disabled_status stage9_build_production_dns_not_called_status stage9_build_production_coupling_disabled_status stage9_build_rhs_untouched_status stage9_build_projection_untouched_status stage9_build_fluid_update_not_called_status stage9_build_fibre_advance_not_called_status stage9_build_production_disabled_policy_status stage9_build_noop_safety_status stage9_build_regression_check_status'''.split()
zeros='''stage9_build_production_coupling_allowed_flag stage9_build_stage_checks_only_flag stage9_build_dns_executed_flag stage9_build_rhs_modified_flag stage9_build_projection_called_flag stage9_build_fluid_update_called_flag stage9_build_fibre_advance_called_flag stage9_build_rhs_hook_called_flag stage9_build_pressure_poisson_modified_flag stage9_build_real_projection_called_flag stage9_build_production_dns_called_flag'''.split()
for k in ones:
    if d.get(k)!=1: raise SystemExit(f'{k} expected 1 got {d.get(k)}')
for k in zeros:
    if d.get(k)!=0: raise SystemExit(f'{k} expected 0 got {d.get(k)}')
print('STAGE 9.1 BUILD REGRESSION CHECK PASSED')
