from pathlib import Path
vals={}
for l in Path('stage9_outputs/fibre_stage9_dependency_gate_check.dat').read_text().splitlines():
    p=l.split()
    if len(p)>=2: vals[p[0]]=float(p[1])
ones='''stage9_gate_stage7_closed_marker_exists stage9_gate_stage7_total_smoke_output_exists stage9_gate_stage7_total_smoke_status stage9_gate_stage7_closed_marker_status stage9_gate_stage7_dependency_status stage9_gate_stage8_closed_marker_exists stage9_gate_stage8_total_smoke_output_exists stage9_gate_stage8_total_smoke_status stage9_gate_stage8_closed_marker_status stage9_gate_stage8_closed_marker_written_flag stage9_gate_stage8_dependency_status stage9_gate_stage8_default_production_disabled_status stage9_gate_stage8_no_production_side_effect_status stage9_gate_stage8_rhs_untouched_status stage9_gate_stage8_pressure_poisson_untouched_status stage9_gate_stage8_projection_untouched_status stage9_gate_stage8_production_dns_not_called_status stage9_gate_stage8_fluid_update_not_called_status stage9_gate_stage8_fibre_advance_not_called_status stage9_gate_stage8_production_disabled_inheritance_status stage9_gate_noop_safety_status stage9_gate_stage9_entry_allowed_flag stage9_gate_stage9_1_allowed_flag stage9_gate_stage9_entry_policy_status stage9_dependency_gate_check_status'''.split()
zeros='''stage9_gate_rhs_hook_called_flag stage9_gate_rhs_modified_flag stage9_gate_pressure_poisson_modified_flag stage9_gate_projection_modified_flag stage9_gate_real_projection_called_flag stage9_gate_production_dns_called_flag stage9_gate_fluid_update_called_flag stage9_gate_fibre_advance_called_flag stage9_gate_production_coupling_allowed_flag'''.split()
for k in ones: assert vals[k]==1.0,k
for k in zeros: assert vals[k]==0.0,k
print('STAGE 9.0 DEPENDENCY GATE CHECK PASSED')
