#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Interface compatibility only. Stage 19.1 must not cd into DECOMP2D_ROOT.
: "${DECOMP2D_ROOT:=${REPO_ROOT}}"

: "${STAGE19_1_ENABLE:=1}"
: "${STAGE19_1_CONFIG_GATE_ENABLE:=1}"
: "${STAGE19_1_DIAGNOSTIC_ONLY:=1}"
: "${STAGE19_1_SINGLE_FIBRE_ONLY:=1}"
: "${STAGE19_1_FAIL_CLOSED:=1}"
: "${STAGE19_1_PHYSICAL_STRUCTURE_ENABLE:=0}"
: "${STAGE19_1_STRUCTURE_STATE_ENABLE:=0}"
: "${STAGE19_1_STRUCTURE_INIT_ENABLE:=0}"
: "${STAGE19_1_FORCE_CANDIDATE_ENABLE:=0}"
: "${STAGE19_1_ADVANCE_CANDIDATE_ENABLE:=0}"
: "${STAGE19_1_COMMIT_ENABLE:=0}"
: "${STAGE19_1_HOOK_ENABLE:=0}"
: "${STAGE19_1_FLUID_FORCE_INPUT_ENABLE:=0}"
: "${STAGE19_1_RHS_SPREADING_ENABLE:=0}"
: "${STAGE19_1_STAGE14_RHS_INJECTION_ENABLE:=0}"
: "${STAGE19_1_RESTART_IO_ENABLE:=0}"
: "${STAGE19_1_STATISTICS_IO_ENABLE:=0}"
: "${STAGE19_1_VISUALIZATION_IO_ENABLE:=0}"
: "${STAGE19_1_CONTACT_MODEL_ENABLE:=0}"
: "${STAGE19_1_FIBRE_FIBRE_COLLISION_ENABLE:=0}"
: "${STAGE19_1_MULTIFIBRE_PRODUCTION_ENABLE:=0}"
: "${STAGE19_1_REQUIRE_STAGE19_0_PASS:=1}"
: "${STAGE19_1_REQUIRE_STAGE18_CLOSED:=1}"
: "${STAGE19_1_ZERO_TOL:=1.0e-14}"
: "${STAGE19_1_AUDIT_TOL:=1.0e-12}"
: "${STAGE19_1_TEST_CASE:=production_physical_structure_config_gate}"

export STAGE19_1_ENABLE STAGE19_1_CONFIG_GATE_ENABLE
export STAGE19_1_DIAGNOSTIC_ONLY STAGE19_1_SINGLE_FIBRE_ONLY STAGE19_1_FAIL_CLOSED
export STAGE19_1_PHYSICAL_STRUCTURE_ENABLE STAGE19_1_STRUCTURE_STATE_ENABLE STAGE19_1_STRUCTURE_INIT_ENABLE
export STAGE19_1_FORCE_CANDIDATE_ENABLE STAGE19_1_ADVANCE_CANDIDATE_ENABLE STAGE19_1_COMMIT_ENABLE STAGE19_1_HOOK_ENABLE
export STAGE19_1_FLUID_FORCE_INPUT_ENABLE STAGE19_1_RHS_SPREADING_ENABLE STAGE19_1_STAGE14_RHS_INJECTION_ENABLE
export STAGE19_1_RESTART_IO_ENABLE STAGE19_1_STATISTICS_IO_ENABLE STAGE19_1_VISUALIZATION_IO_ENABLE
export STAGE19_1_CONTACT_MODEL_ENABLE STAGE19_1_FIBRE_FIBRE_COLLISION_ENABLE STAGE19_1_MULTIFIBRE_PRODUCTION_ENABLE
export STAGE19_1_REQUIRE_STAGE19_0_PASS STAGE19_1_REQUIRE_STAGE18_CLOSED
export STAGE19_1_ZERO_TOL STAGE19_1_AUDIT_TOL STAGE19_1_TEST_CASE

mkdir -p "${REPO_ROOT}/stage19_outputs"
OUTPUT="${REPO_ROOT}/stage19_outputs/fibre_stage19_1_physical_structure_config_gate.dat"

python3 "${SCRIPT_DIR}/assert_stage19_1_physical_structure_config_gate.py" \
  --repo-root "${REPO_ROOT}" \
  --output "${OUTPUT}"
