from pathlib import Path
vals={}
for l in Path('stage8_outputs/fibre_stage8_total_smoke_check.dat').read_text().splitlines():
    p=l.split()
    if len(p)>=2: vals[p[0]]=float(p[1])
ones='''stage8_total_stage7_closed_marker_exists stage8_total_stage7_total_smoke_output_exists stage8_total_stage7_total_smoke_status stage8_total_stage7_closed_marker_status stage8_total_stage7_dependency_status stage8_total_stage8_0_output_exists stage8_total_stage8_1_output_exists stage8_total_stage8_2_output_exists stage8_total_stage8_3_output_exists stage8_total_stage8_4_output_exists stage8_total_stage8_5_output_exists stage8_total_stage8_6_output_exists stage8_total_stage8_7_output_exists stage8_total_stage8_8_output_exists stage8_total_stage8_9_output_exists stage8_total_all_stage8_outputs_exist stage8_total_stage8_0_status stage8_total_stage8_1_status stage8_total_stage8_2_status stage8_total_stage8_3_status stage8_total_stage8_4_status stage8_total_stage8_5_status stage8_total_stage8_6_status stage8_total_stage8_7_status stage8_total_stage8_8_status stage8_total_stage8_9_status stage8_total_all_stage8_status stage8_total_config_summary_status stage8_total_numeric_summary_status stage8_total_conservation_power_rho_summary_status stage8_total_boundary_summary_status stage8_total_rk_summary_status stage8_total_no_production_side_effect_status stage8_total_closed_marker_written_flag stage8_total_closed_marker_status stage8_total_smoke_check_status'''.split()
for k in ones: assert vals[k]==1.0,k
assert Path('stage8_outputs/STAGE8_CLOSED.md').is_file()
print('STAGE 8.10 TOTAL SMOKE CHECK PASSED')
