from pathlib import Path
vals={}
for l in Path('stage8_outputs/fibre_stage8_integrated_audit_check.dat').read_text().splitlines():
    p=l.split()
    if len(p)>=2: vals[p[0]]=float(p[1])
ones='''stage8_integrated_stage7_closed_marker_exists stage8_integrated_stage7_total_smoke_output_exists stage8_integrated_stage7_total_smoke_status stage8_integrated_stage7_closed_marker_status stage8_integrated_stage8_0_output_exists stage8_integrated_stage8_0_status stage8_integrated_stage8_1_output_exists stage8_integrated_stage8_1_status stage8_integrated_stage8_2_output_exists stage8_integrated_stage8_2_status stage8_integrated_stage8_3_output_exists stage8_integrated_stage8_3_status stage8_integrated_stage8_4_output_exists stage8_integrated_stage8_4_status stage8_integrated_stage8_5_output_exists stage8_integrated_stage8_5_status stage8_integrated_stage8_6_output_exists stage8_integrated_stage8_6_status stage8_integrated_stage8_7_output_exists stage8_integrated_stage8_7_status stage8_integrated_stage8_8_output_exists stage8_integrated_stage8_8_status stage8_integrated_dependency_status stage8_integrated_safe_workflow_status stage8_integrated_action_reaction_status stage8_integrated_force_conservation_status stage8_integrated_pair_power_dissipative_flag stage8_integrated_pair_power_status stage8_integrated_fluid_power_consistency_status stage8_integrated_force_density_convention_flag stage8_integrated_spreading_no_rho_division_flag stage8_integrated_force_density_convention_status stage8_integrated_rho_convention_status stage8_integrated_blocked_rejected_flag stage8_integrated_blocked_exclusion_status stage8_integrated_no_production_side_effect_status stage8_integrated_noop_safety_status stage8_integrated_audit_check_status'''.split()
zeros='''stage8_integrated_safe_blocked_count stage8_integrated_safe_unsafe_count stage8_integrated_double_division_detected_flag stage8_integrated_production_rhs_modified_flag stage8_integrated_stage6_rhs_hook_production_called_flag stage8_integrated_pressure_poisson_modified_flag stage8_integrated_projection_modified_flag stage8_integrated_real_projection_called_flag stage8_integrated_production_dns_called_flag stage8_integrated_fluid_update_called_flag stage8_integrated_fibre_advance_called_flag stage8_integrated_noop_rhs_modified_flag'''.split()
for k in ones: assert vals[k]==1.0,k
for k in zeros: assert vals[k]==0.0,k
assert vals['stage8_integrated_safe_valid_count']>=2
assert vals['stage8_integrated_force_density_norm_max']>1e-14
assert vals['stage8_integrated_action_reaction_error_max']<=1e-12
assert vals['stage8_integrated_force_conservation_abs_error']<=1e-12
assert vals['stage8_integrated_force_conservation_relative_error']<=1e-12
assert vals['stage8_integrated_force_conservation_x_error']<=1e-12
assert vals['stage8_integrated_force_conservation_y_error']<=1e-12
assert vals['stage8_integrated_force_conservation_z_error']<=1e-12
assert vals['stage8_integrated_pair_power_error']<=1e-12
assert vals['stage8_integrated_fluid_power_consistency_error']<=1e-10
assert vals['stage8_integrated_force_buffer_change_with_rho_max']<=1e-14
assert vals['stage8_integrated_rho2_expected_error_max']<=1e-12
assert vals['stage8_integrated_rho4_expected_error_max']<=1e-12
assert vals['stage8_integrated_rho_scaling_error']<=1e-12
assert vals['stage8_integrated_blocked_force_buffer_norm_max']<=1e-14
assert vals['stage8_integrated_blocked_power_abs_max']<=1e-14
assert vals['stage8_integrated_noop_rhs_change_max']<=1e-14
if vals['stage8_integrated_controlled_rhs_hook_available_flag']==1.0: assert vals['stage8_integrated_controlled_rhs_hook_called_flag']==1.0
if 'stage8_integrated_rho2_injected_flag' in vals: assert vals['stage8_integrated_rho2_injected_flag']==1.0
if 'stage8_integrated_rho4_injected_flag' in vals: assert vals['stage8_integrated_rho4_injected_flag']==1.0
print('STAGE 8.9 INTEGRATED AUDIT CHECK PASSED')
