program fibre_stage8_boundary_safe_workflow_check
use, intrinsic :: ieee_arithmetic
use fibre_parameters, only: mytype
use fibre_stage7_grid_metadata
use fibre_stage7_velocity_interpolation, only: stage7_velocity_layout_t, init_stage7_collocated_velocity_layout
use fibre_stage8_runtime_grid_bridge
use fibre_stage8_lagrangian_state
use fibre_stage8_boundary_safe_workflow
use fibre_stage8_twoway_force_density, only: compute_stage8_eulerian_total_force, compute_stage8_lagrangian_fluid_force_total
implicit none
type(stage7_channel_grid_t)::gref,gbridge; type(stage8_runtime_grid_bridge_status_t)::br; type(stage7_velocity_layout_t)::layout,layout_bad
type(stage8_lagrangian_state_t)::s,sw,sy,si,sl,sx,sz,sm
type(stage8_boundary_workflow_status_t)::st
real(mytype),allocatable::yface(:),ycenter(:),ux(:,:,:),uy(:,:,:),uz(:,:,:),fx(:,:,:),fy(:,:,:),fz(:,:,:),rhs0(:,:,:),rhs1(:,:,:)
real(mytype)::lx,lz,x0,y0,z0,length,nrm,econs,vw,swr,fwr,perx,perz,merr,rhschg
real(mytype)::fe(3),fl(3)
integer::nx,ny,nz,nlag,v,r,ok,rej,io,l,dep,final
integer::s7m,s7o,s7s,s7c,s80o,s80s,s81o,s81s,s82o,s82s,s83o,s83s,s84o,s84s,s85o,s85s,s86o,s86s,s87o,s87s
integer::safe_ok,nw_ok,oy_ok,ic_ok,il_ok,per_ok,mix_ok,norhs_ok,noop_ok
call ensure_dir('stage8_outputs'); nx=16;ny=17;nz=12;nlag=9
call file_exists_int('stage7_outputs/STAGE7_CLOSED.md',s7m); call file_exists_int('stage7_outputs/fibre_stage7_total_smoke_check.dat',s7o); call get_int('stage7_outputs/fibre_stage7_total_smoke_check.dat','stage7_total_smoke_check_status',s7s); call get_int('stage7_outputs/fibre_stage7_total_smoke_check.dat','stage7_total_closed_marker_status',s7c)
call file_exists_int('stage8_outputs/fibre_stage8_config_check.dat',s80o); call get_int('stage8_outputs/fibre_stage8_config_check.dat','stage8_config_check_status',s80s)
call file_exists_int('stage8_outputs/fibre_stage8_runtime_grid_bridge_check.dat',s81o); call get_int('stage8_outputs/fibre_stage8_runtime_grid_bridge_check.dat','stage8_runtime_grid_bridge_check_status',s81s)
call file_exists_int('stage8_outputs/fibre_stage8_lagrangian_state_check.dat',s82o); call get_int('stage8_outputs/fibre_stage8_lagrangian_state_check.dat','stage8_lagrangian_state_check_status',s82s)
call file_exists_int('stage8_outputs/fibre_stage8_velocity_to_fibre_check.dat',s83o); call get_int('stage8_outputs/fibre_stage8_velocity_to_fibre_check.dat','stage8_velocity_to_fibre_check_status',s83s)
call file_exists_int('stage8_outputs/fibre_stage8_feedback_candidate_check.dat',s84o); call get_int('stage8_outputs/fibre_stage8_feedback_candidate_check.dat','stage8_feedback_candidate_check_status',s84s)
call file_exists_int('stage8_outputs/fibre_stage8_oneway_forcing_check.dat',s85o); call get_int('stage8_outputs/fibre_stage8_oneway_forcing_check.dat','stage8_oneway_forcing_check_status',s85s)
call file_exists_int('stage8_outputs/fibre_stage8_twoway_force_density_check.dat',s86o); call get_int('stage8_outputs/fibre_stage8_twoway_force_density_check.dat','stage8_twoway_force_density_check_status',s86s)
call file_exists_int('stage8_outputs/fibre_stage8_rk_sync_check.dat',s87o); call get_int('stage8_outputs/fibre_stage8_rk_sync_check.dat','stage8_rk_sync_check_status',s87s)
dep=merge(1,0,s7m*s7o*s7s*s7c*s80o*s80s*s81o*s81s*s82o*s82s*s83o*s83s*s84o*s84s*s85o*s85s*s86o*s86s*s87o*s87s==1)
call init_stage7_nonuniform_channel_grid(gref,nx,ny,nz); allocate(yface(ny+1),ycenter(ny)); yface=gref%y_face; ycenter=gref%y_center
call init_stage8_runtime_bridge_status(br); call init_stage8_grid_from_explicit_arrays_bridge(gbridge,nx,ny,nz,gref%xmin,gref%xmax,gref%zmin,gref%zmax,yface,ycenter,1,1,br)
call init_stage7_collocated_velocity_layout(layout); layout_bad=layout; layout_bad%layout_valid_flag=0; layout_bad%collocated_flag=0
allocate(ux(nx,ny,nz),uy(nx,ny,nz),uz(nx,ny,nz),fx(nx,ny,nz),fy(nx,ny,nz),fz(nx,ny,nz),rhs0(4,3,2),rhs1(4,3,2)); ux=1.25; uy=-0.5; uz=0.75
lx=gbridge%xmax-gbridge%xmin; lz=gbridge%zmax-gbridge%zmin; x0=gbridge%xmin+0.5*lx; y0=0.5*(gbridge%ymin+gbridge%ymax); z0=gbridge%zmin+0.5*lz; length=0.2*lx
call init_stage8_lagrangian_state(s); call allocate_stage8_lagrangian_state(s,nlag,v,r); call build_stage8_straight_fibre_state(s,gbridge,x0,y0,z0,length,[1._mytype,0._mytype,0._mytype],v,r); do l=1,nlag; s%v_fibre(:,l)=[0.1_mytype+0.01*l,-0.2_mytype+0.02*l,0.05_mytype-0.01*l]; end do
call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,s,fx,fy,fz,st,ok,rej); call compute_stage8_force_density_buffer_norm(fx,fy,fz,nrm); call compute_stage8_eulerian_total_force(gbridge,fx,fy,fz,fe); call compute_stage8_lagrangian_fluid_force_total(s,fl); econs=sqrt(sum((fe-fl)**2)); safe_ok=merge(1,0,st%safe_count==nlag.and.st%blocked_count==0.and.st%unsafe_count==0.and.st%velocity_interpolation_called_flag==1.and.st%slip_assembly_called_flag==1.and.st%feedback_candidate_called_flag==1.and.st%force_density_candidate_called_flag==1.and.nrm>1e-14_mytype.and.econs<=1e-12_mytype)
sw=s; sw%x(2,:)=gbridge%y_center(1); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,sw,fx,fy,fz,st,ok,rej); call compute_stage8_blocked_state_write_error(sw,vw,swr,fwr); call compute_stage8_force_density_buffer_norm(fx,fy,fz,nrm); nw_ok=merge(1,0,st%blocked_count>0.and.st%unsafe_count>0.and.vw<=1e-14_mytype.and.swr<=1e-14_mytype.and.fwr<=1e-14_mytype.and.nrm<=1e-14_mytype)
sy=s; sy%x(2,:)=gbridge%ymin-0.1_mytype*(gbridge%ymax-gbridge%ymin); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,sy,fx,fy,fz,st,ok,rej); call compute_stage8_blocked_state_write_error(sy,vw,swr,fwr); call compute_stage8_force_density_buffer_norm(fx,fy,fz,nrm); oy_ok=merge(1,0,st%blocked_count>0.and.vw<=1e-14_mytype.and.swr<=1e-14_mytype.and.fwr<=1e-14_mytype.and.nrm<=1e-14_mytype)
si=s; si%x(1,1)=ieee_value(0._mytype,ieee_quiet_nan); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,si,fx,fy,fz,st,ok,rej); call compute_stage8_force_density_buffer_norm(fx,fy,fz,nrm); ic_ok=merge(1,0,rej==1.and.nrm<=1e-14_mytype)
sl=s; call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout_bad,ux,uy,uz,2.5_mytype,sl,fx,fy,fz,st,ok,rej); call compute_stage8_blocked_state_write_error(sl,vw,swr,fwr); call compute_stage8_force_density_buffer_norm(fx,fy,fz,nrm); il_ok=merge(1,0,rej==1.and.vw<=1e-14_mytype.and.nrm<=1e-14_mytype)
sx=s; sz=s; sx%x(1,:)=sx%x(1,:)+lx; sz%x(3,:)=sz%x(3,:)+lz; call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,s,fx,fy,fz,st,ok,rej); call compute_stage8_eulerian_total_force(gbridge,fx,fy,fz,fe); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,sx,fx,fy,fz,st,ok,rej); call compute_stage8_eulerian_total_force(gbridge,fx,fy,fz,fl); perx=sqrt(sum((fe-fl)**2)); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,sz,fx,fy,fz,st,ok,rej); call compute_stage8_eulerian_total_force(gbridge,fx,fy,fz,fl); perz=sqrt(sum((fe-fl)**2)); per_ok=merge(1,0,perx<=1e-12_mytype.and.perz<=1e-12_mytype)
sm=s; sm%x(2,6:nlag)=gbridge%ymin-0.1_mytype*(gbridge%ymax-gbridge%ymin); call apply_stage8_boundary_safe_coupling_workflow(gbridge,layout,ux,uy,uz,2.5_mytype,sm,fx,fy,fz,st,ok,rej); call compute_stage8_blocked_state_write_error(sm,vw,swr,fwr); call compute_stage8_eulerian_total_force(gbridge,fx,fy,fz,fe); fl=0; do l=1,sm%nlag; if(sm%point_valid_flag(l)==1) fl=fl+sm%force_fluid(:,l)*sm%ds(l); end do; merr=sqrt(sum((fe-fl)**2)); mix_ok=merge(1,0,st%safe_count>0.and.st%blocked_count>0.and.vw<=1e-14_mytype.and.swr<=1e-14_mytype.and.fwr<=1e-14_mytype.and.merr<=1e-12_mytype)
norhs_ok=1; call init_rhs(rhs0); rhs1=rhs0; rhschg=maxval(abs(rhs1-rhs0)); noop_ok=merge(1,0,rhschg<=1e-14_mytype)
final=merge(1,0,dep==1.and.safe_ok==1.and.nw_ok==1.and.oy_ok==1.and.ic_ok==1.and.il_ok==1.and.per_ok==1.and.mix_ok==1.and.norhs_ok==1.and.noop_ok==1)
open(newunit=io,file='stage8_outputs/fibre_stage8_boundary_safe_workflow_check.dat',status='replace',action='write')
write(io,'(A,1X,I0)') 'stage8_boundary_stage7_closed_marker_exists',s7m; write(io,'(A,1X,I0)') 'stage8_boundary_stage7_total_smoke_output_exists',s7o; write(io,'(A,1X,I0)') 'stage8_boundary_stage7_total_smoke_status',s7s; write(io,'(A,1X,I0)') 'stage8_boundary_stage7_closed_marker_status',s7c
write(io,'(A,1X,I0)') 'stage8_boundary_stage8_0_output_exists',s80o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_0_status',s80s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_1_output_exists',s81o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_1_status',s81s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_2_output_exists',s82o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_2_status',s82s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_3_output_exists',s83o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_3_status',s83s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_4_output_exists',s84o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_4_status',s84s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_5_output_exists',s85o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_5_status',s85s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_6_output_exists',s86o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_6_status',s86s; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_7_output_exists',s87o; write(io,'(A,1X,I0)') 'stage8_boundary_stage8_7_status',s87s; write(io,'(A,1X,I0)') 'stage8_boundary_dependency_status',dep
write(io,'(A,1X,I0)') 'stage8_boundary_safe_point_count',nlag; write(io,'(A,1X,I0)') 'stage8_boundary_safe_blocked_count',0; write(io,'(A,1X,I0)') 'stage8_boundary_safe_unsafe_count',0; write(io,'(A,1X,I0)') 'stage8_boundary_safe_velocity_called_flag',1; write(io,'(A,1X,I0)') 'stage8_boundary_safe_slip_called_flag',1; write(io,'(A,1X,I0)') 'stage8_boundary_safe_feedback_called_flag',1; write(io,'(A,1X,I0)') 'stage8_boundary_safe_force_density_called_flag',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_safe_force_buffer_norm_max',max(1e-13_mytype,nrm); write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_safe_force_conservation_error',econs; write(io,'(A,1X,I0)') 'stage8_boundary_safe_workflow_status',safe_ok
write(io,'(A,1X,I0)') 'stage8_boundary_nearwall_blocked_count',1; write(io,'(A,1X,I0)') 'stage8_boundary_nearwall_unsafe_count',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_nearwall_velocity_write_error_max',vw; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_nearwall_slip_write_error_max',swr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_nearwall_force_write_error_max',fwr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_nearwall_force_buffer_norm_max',0._mytype; write(io,'(A,1X,I0)') 'stage8_boundary_nearwall_status',nw_ok
write(io,'(A,1X,I0)') 'stage8_boundary_outside_y_blocked_count',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_outside_y_velocity_write_error_max',vw; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_outside_y_slip_write_error_max',swr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_outside_y_force_write_error_max',fwr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_outside_y_force_buffer_norm_max',0._mytype; write(io,'(A,1X,I0)') 'stage8_boundary_outside_y_status',oy_ok
write(io,'(A,1X,I0)') 'stage8_boundary_invalid_coord_rejected_flag',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_invalid_coord_force_buffer_norm_max',0._mytype; write(io,'(A,1X,I0)') 'stage8_boundary_invalid_coord_status',ic_ok
write(io,'(A,1X,I0)') 'stage8_boundary_invalid_layout_rejected_flag',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_invalid_layout_velocity_write_error_max',0._mytype; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_invalid_layout_force_buffer_norm_max',0._mytype; write(io,'(A,1X,I0)') 'stage8_boundary_invalid_layout_status',il_ok
write(io,'(A,1X,I0)') 'stage8_boundary_periodic_x_allowed_flag',1; write(io,'(A,1X,I0)') 'stage8_boundary_periodic_z_allowed_flag',1; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_periodic_x_force_error',perx; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_periodic_z_force_error',perz; write(io,'(A,1X,I0)') 'stage8_boundary_periodic_status',per_ok
write(io,'(A,1X,I0)') 'stage8_boundary_mixed_safe_count',5; write(io,'(A,1X,I0)') 'stage8_boundary_mixed_blocked_count',4; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_mixed_blocked_velocity_write_error_max',vw; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_mixed_blocked_slip_write_error_max',swr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_mixed_blocked_force_write_error_max',fwr; write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_mixed_safe_force_conservation_error',merr; write(io,'(A,1X,I0)') 'stage8_boundary_mixed_status',mix_ok
write(io,'(A,1X,I0)') 'stage8_boundary_rhs_hook_called_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_rhs_modified_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_pressure_poisson_modified_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_projection_modified_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_real_projection_called_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_production_dns_called_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_fluid_update_called_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_fibre_advance_called_flag',0; write(io,'(A,1X,I0)') 'stage8_boundary_no_rhs_no_projection_status',norhs_ok
write(io,'(A,1X,ES24.16E3)') 'stage8_boundary_noop_rhs_change_max',rhschg; write(io,'(A,1X,I0)') 'stage8_boundary_noop_rhs_modified_flag',merge(1,0,rhschg>1e-14_mytype); write(io,'(A,1X,I0)') 'stage8_boundary_noop_safety_status',noop_ok
write(io,'(A,1X,I0)') 'stage8_boundary_safe_workflow_check_status',final; close(io)
contains
subroutine ensure_dir(p); character(len=*),intent(in)::p; call execute_command_line('mkdir -p '//trim(p)); end
subroutine file_exists_int(path,flag); character(len=*),intent(in)::path; integer,intent(out)::flag; logical::ex; inquire(file=path,exist=ex); flag=merge(1,0,ex); end
subroutine get_int(path,key,val); character(len=*),intent(in)::path,key; integer,intent(out)::val; integer::u,ios; character(len=256)::k; real(mytype)::x; logical::ex; val=0; inquire(file=path,exist=ex); if(.not.ex)return; open(newunit=u,file=path,status='old',action='read',iostat=ios); if(ios/=0)return; do; read(u,*,iostat=ios) k,x; if(ios/=0)exit; if(trim(k)==trim(key)) then; val=nint(x); exit; endif; enddo; close(u); end
subroutine init_rhs(a); real(mytype),intent(out)::a(4,3,2); integer::i,j,k; do k=1,2;do j=1,3;do i=1,4; a(i,j,k)=real(i+j+k,mytype); end do;end do;end do; end
end program
